[api]
port = 8000
ipfs_api_url = ""
ipfs_addrinfo = ""
submit_challenge = true
submit_proof = true

[chain]
addr_prefix="sunrise"
keyring_backend="test"
home_path="/Users/admin/.sunrise"
publisher_account="val"
fees="10000urise"
cometbft_rpc="http://localhost:26657"
vote_extension_period=2