[api]
port = 8000
ipfs_api_url = ""

[chain]
addr_prefix="sunrise"
keyring_backend="test"
home_path="/Users/admin/.sunrise"
publisher_account="validator"
fees="10000uvrise"
cometbft_rpc="http://localhost:26657"
vote_extension_period=2