[api]
port = 8000
ipfs_api_url = ""
ipfs_address_info = ""

[chain]
address_prefix="sunrise"
home_path="/home/ubuntu/.sunrise"
keyring_backend="test"
sunrised_rpc="http://localhost:26657"

[publish]
publisher_account="your_publisher"
publish_fees="10000urise"

[validator]
proof_deputy_account="your_deputy"
validator_address=""
proof_fees="10000urise"
proof_interval=5

[rollkit]
port=7980
data_shard_count=5
parity_shard_count=5

[optimism]
listen_address="127.0.0.1"
port=3100
data_shard_count=10
parity_shard_count=10
