[api]
port = 8000
ipfs_api_url = ""
ipfs_addrinfo = ""
submit_challenge = true
submit_proof = true

[chain]
addr_prefix="sunrise"
keyring_backend="test"
home_path="/home/ubuntu/.sunrise"
publisher_account="your_publisher"
proof_deputy_account="your_deputy"
validator_address="" # if you are not a validator, leave it empty
fees="10000urise"
sunrised_rpc="http://localhost:26657"
validator_proof_interval=5

[rollkit]
port=7980
data_shard_count=5
parity_shard_count=5
