[api]
port = 8000
ipfs_api_url = ""
ipfs_addrinfo = ""
submit_challenge = true
submit_proof = true

[chain]
addr_prefix="sunrise"
keyring_backend="test"
home_path="/home/ubuntu/.sunrise"
publisher_account="your_publisher"
proof_deputy_account="your_deputy"
validator_address="sunrisevaloper1a8jcsmla6heu99ldtazc27dna4qcd4jyv75vcz"
fees="10000urise"
cometbft_rpc="http://localhost:26657"

[rollkit]
port=7980
data_shard_count=5
parity_shard_count=5
